AllCops:
  Exclude:
    - 'db/**/*'
  RunRailsCops: true

Documentation:
  Enabled: false

StringLiterals:
  EnforcedStyle: single_quotes

Metrics/LineLength:
  Max: 120

Style/FileName:
  Enabled: false
